export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const STAFF_LIST_REQUEST = "STAFFS_LIST_REQUEST";
export const STAFF_LIST_SUCCESS = "STAFFS_LIST_SUCCESS";
export const STAFF_LIST_FAIL = "STAFFS_LIST_FAIL";

export const LIBRARIAN_LIST_REQUEST = "LIBRARIANS_LIST_REQUEST";
export const LIBRARIAN_LIST_SUCCESS = "LIBRARIANS_LIST_SUCCESS";
export const LIBRARIAN_LIST_FAIL = "LIBRARIANS_LIST_FAIL";

export const STAFFS_COUNT_REQUEST = "STAFFS_COUNT_REQUEST";
export const STAFFS_COUNT_SUCCESS = "STAFFS_COUNT_SUCCESS";
export const STAFFS_COUNT_FAIL = "STAFFS_COUNT_FAIL";

export const LIBRARIANS_COUNT_REQUEST = "LIBRARIANS_COUNT_REQUEST";
export const LIBRARIANS_COUNT_SUCCESS = "LIBRARIANS_COUNT_SUCCESS";
export const LIBRARIANS_COUNT_FAIL = "LIBRARIANS_COUNT_FAIL";

export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL"

export const STUDENT_CREATE_REQUEST = "STUDENT_CREATE_REQUEST";
export const STUDENT_CREATE_SUCCESS = "STUDENT_CREATE_SUCCESS";
export const STUDENT_CREATE_FAIL = "STUDENT_CREATE_FAIL";

export const STUDENT_LIST_REQUEST = "STUDENT_LIST_REQUEST";
export const STUDENT_LIST_SUCCESS = "STUDENT_LIST_SUCCESS";
export const STUDENT_LIST_FAIL = "STUDENT_LIST_FAIL";

export const STUDENT_UPDATE_REQUEST = "STUDENT_UPDATE_REQUEST";
export const STUDENT_UPDATE_SUCCESS = "STUDENT_UPDATE_SUCCESS";
export const STUDENT_UPDATE_FAIL = "STUDENT_UPDATE_FAIL";

export const STUDENT_DELETE_REQUEST = "STUDENT_DELETE_REQUEST";
export const STUDENT_DELETE_SUCCESS = "STUDENT_DELETE_SUCCESS";
export const STUDENT_DELETE_FAIL = "STUDENT_DELETE_FAIL"

export const LIBRARYHISTORY_LIST_REQUEST = "LIBRARYHISTORY_LIST_REQUEST";
export const LIBRARYHISTORY_LIST_SUCCESS = "LIBRARYHISTORY_LIST_SUCCESS";
export const LIBRARYHISTORY_LIST_FAIL = "LIBRARYHISTORY_LIST_FAIL";

export const LIBRARYHISTORY_UPDATE_REQUEST = "LIBRARYHISTORY_UPDATE_REQUEST";
export const LIBRARYHISTORY_UPDATE_SUCCESS = "LIBRARYHISTORY_UPDATE_SUCCESS";
export const LIBRARYHISTORY_UPDATE_FAIL = "LIBRARYHISTORY_UPDATE_FAIL";

export const LIBRARYHISTORY_DELETE_REQUEST = "LIBRARYHISTORY_DELETE_REQUEST";
export const LIBRARYHISTORY_DELETE_SUCCESS = "LIBRARYHISTORY_DELETE_SUCCESS";
export const LIBRARYHISTORY_DELETE_FAIL = "LIBRARYHISTORY_DELETE_FAIL"

export const LIBRARYHISTORY_CREATE_REQUEST = "LIBRARYHISTORY_CREATE_REQUEST";
export const LIBRARYHISTORY_CREATE_SUCCESS = "LIBRARYHISTORY_CREATE_SUCCESS";
export const LIBRARYHISTORY_CREATE_FAIL = "LIBRARYHISTORY_CREATE_FAIL"

export const FEEHISTORY_LIST_REQUEST = "FEEHISTORY_LIST_REQUEST";
export const FEEHISTORY_LIST_SUCCESS = "FEEHISTORY_LIST_SUCCESS";
export const FEEHISTORY_LIST_FAIL = "FEEHISTORY_LIST_FAIL";

export const FEEHISTORY_UPDATE_REQUEST = "FEEHISTORY_UPDATE_REQUEST";
export const FEEHISTORY_UPDATE_SUCCESS = "FEEHISTORY_UPDATE_SUCCESS";
export const FEEHISTORY_UPDATE_FAIL = "FEEHISTORY_UPDATE_FAIL";

export const FEEHISTORY_DELETE_REQUEST = "FEEHISTORY_DELETE_REQUEST";
export const FEEHISTORY_DELETE_SUCCESS = "FEEHISTORY_DELETE_SUCCESS";
export const FEEHISTORY_DELETE_FAIL = "FEEHISTORY_DELETE_FAIL"

export const FEEHISTORY_CREATE_REQUEST = "FEEHISTORY_CREATE_REQUEST";
export const FEEHISTORY_CREATE_SUCCESS = "FEEHISTORY_CREATE_SUCCESS";
export const FEEHISTORY_CREATE_FAIL = "FEEHISTORY_CREATE_FAIL"